{% set name = "pyexcel-io" %}
{% set version = "0.5.17" %}
{% set sha256 = "020a7ac46793710d87928e1cea5c9aa3cd634e70ca5343c73dc1cb9f7de00e94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python
    - lml >=0.0.4

test:
  imports:
    - pyexcel_io
    - pyexcel_io.database
    - pyexcel_io.database.exporters
    - pyexcel_io.database.importers
    - pyexcel_io.readers
    - pyexcel_io.writers


about:
  home: https://github.com/pyexcel/pyexcel-io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'One interface to read and write the data in various excel formats, import the data into and export the data from databases'
  description: |
   'A python library to read and write structured data in csv, zipped csv ' +
    'format and to/from databases' +
    ''
  doc_url: https://readthedocs.org/projects/pyexcel-io/
  dev_url: https://github.com/pyexcel/pyexcel-io

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
