{% set name = "pyexcel-io" %}
{% set version = "0.5.7" %}
{% set sha256 = "5cf5ccf7750ca130640277f31178b6284a4f9f0f0d1d41f28f419b67ce26132b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lml ==0.0.1

test:
  imports:
    - pyexcel_io
    - pyexcel_io.database
    - pyexcel_io.database.exporters
    - pyexcel_io.database.importers
    - pyexcel_io.readers
    - pyexcel_io.writers


about:
  home: https://github.com/pyexcel/pyexcel-io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'One interface to read and write the data in various excel formats, import the data into and export the data from databases'
  description: |
   'A python library to read and write structured data in csv, zipped csv ' +
    'format and to/from databases' +
    ''
  doc_url: https://readthedocs.org/projects/pyexcel-io/
  dev_url: https://github.com/pyexcel/pyexcel-io

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
