travis:
  secure:
    BINSTAR_TOKEN: PFe9CCCp6lIil/Kgf6ty9QUgtUxRPHzpyRRHbQO1+9OOEMDt3Cg6lc1WyvW3fNbzX20b3GRfsT1ckg9IhKXcRkLw442b0+vmhvr2+Vf17+deNP67EbV/oBrW1dxSqgV7PUOEIHXrobrf79d480I72R6d1RJkNGPQsUmuu3LgmDiNmjMeAS4JCPeEbPLFAx31CtgLW9jt1VZK6+PfA/OfCx5LVdQfkdA4XPTtR3PSg5HqYloT9YkeeyltkaVREsrrxqSDxsYXN4Y6IYMyE3WKRCbP1ogMc3nsEST9d4Ee9W6IfT83hh7HtKLeQH47O/jrIglBNnM1MPWQ3EtI2o+GZaBXzPIadB6+J44vWj3OiI0ZObjpzi0bIR4qOtglgkemIj2ODvx8sr8QVXCpaP6UUhSUNGKBCEYozW1xufxx4j689dLqSHVv7ogeDxG/I30xC7S8F5krb5QFC9kN+21VjHER24pmsdEbGXnx2L94ThJYfMSC3eP08fSS/Gl/vJJKeu+HOmehFsB+TQnXF2vZMN1WxQeXtpTh6b9XpdCGU2NmwCF/77sunEyqIm149htLsiy72EQZav5ks2cW9S6Ny2q1qqFLbODBeGiAasu3w4avHgLb0pAF71uN26UNhM7Hyk7J6VZMxUDs8F6sDqyXRBLjoKkY/IJ8BTmbTxzDQHo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
