travis:
  secure:
    BINSTAR_TOKEN: iiO4UiktARlnqPtYmU0u/RC5Zh9jBVzGMoqWn+44cMOztuica2DHRVYcwxAhFVw/wPPnB3uzNqb0e7rGwWfyY+qwon1BLifUhlFh59WLBPkMSmsM2XOEiV3ZqSynx3K4VZfdRXb5JFUHStgBcXk9Oq32PVyqlp2o+71J/jfJcmY01XTjU3ic2xBUgSobhasVhhiTM8n5OshelG6ppa7sKtMTv60oiocYfmfrEDT4DXOv4+LvAhV8rSwc0zLMXHyo7d1YXSdcK13PtnYDYuKAM0G62TgP9KT55EhLLfYsPsejg2ii2Ngtp9i4lJZ2ZpEtz/+NxR0MW6KawYX8DjcLd9wIo4Wq2hdZuV21n07oAu3TfM1+Xw5+qM/pdVavTQNq84+jf3HN9tyTgAqoYHhQZ8aG0afDIx3E27xbDy8wVIE48vBYcH+kt159xPLFB0Y/j+nxUCTeY+VAf5bZ2rNFBWfiLFEJUH9JQ03nETkfxhQ1WvZpnf/aYM/Vixw0CBy/VE2n27TDuMgN700U+wPe3MOo8ul2lh0Kmj9ko/PLhjSWm/grqaaFmkjYx5bfOfiZ24TioeftRiruJM4psUQ60fjLbrqicGCMI+IJS/2b8UHkQCLSesuff6Oy8dJJVbKIBRMNpeu2MP8AyWssBGIckkgwuqXKbtzFAgdUjXOQiTs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
